# Template that is automatically filled in using Python; the placeholders are substituted with values from the JSON file.

# Ensure that the necessary prefixes are included in the query as these are not automatically filled in.
PREFIX db: <http://data.local/rdf/ontology/>
PREFIX dbo: <http://um-cds/ontologies/databaseontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX roo: <http://www.cancerdata.org/roo/>

DELETE { ?tablerow dbo:has_column ?variable . }

WHERE {
    ?tablerow rdf:type db:databasename .
    ?variable rdf:type db:databasename.localvariable .
}