# Template that is automatically filled in using Python; the placeholders are substituted with values from the JSON file.

# Ensure that the necessary prefixes are included in the query as these are not automatically filled in.
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbo: <http://um-cds/ontologies/databaseontology/>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>

INSERT {
    GRAPH <http://annotation.local/> {
        ?term rdf:type owl:Class ;
            owl:equivalentClass
                [
                    owl:intersectionOf
                        ( [
                              rdf:type owl:Restriction ;
                              owl:onProperty dbo:cell_of ;
                              owl:someValuesFrom ?superClass ;
                          ]
                            [
                                rdf:type owl:Restriction ;
                                owl:onProperty dbo:has_value ;
                                owl:hasValue ?localValue ;
                            ]
                        ) ;
                    rdf:type owl:Class
                ] ;
            rdfs:subClassOf ?superClass .
    }
} WHERE {
    BIND(<%s> AS ?term) .
    BIND(<%s> AS ?superClass) .
    BIND("%s"^^xsd:string AS ?localValue) .

}