# Template to autofill where SPARQL's bind cannot and Python can.
# That is, all strings with "REPLACEME" should be replaced as follows:
# REPLACEME1 _database name
# REPLACEME2 actual variable local definition

PREFIX db: <http://data.local/rdf/ontology/>
PREFIX dbo: <http://um-cds/ontologies/databaseontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>


DELETE { ?tablerow dbo:has_column ?variable . }

WHERE {
    ?tablerow rdf:type db:REPLACEME1 .
    ?variable rdf:type db:REPLACEME1.REPLACEME2 .
}