# Template to autofill where SPARQL's bind cannot and Python can.
# That is, all strings with "REPLACEME" should be replaced as follows:
# REPLACEME1 _database name
# REPLACEME5 class name
# REPLACEME8 label

PREFIX db: <http://data.local/rdf/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT {
    GRAPH <http://annotation.local/> {

        db:REPLACEME1.REPLACEME5 rdf:type owl:Class.

        db:REPLACEME1.REPLACEME5 rdfs:label "REPLACEME8".

    }
}

WHERE {

    ?tablerow rdf:type db:mock .

}