# Template to autofill where SPARQL's bind cannot and Python can.
# That is, all strings with "REPLACEME" should be replaced as follows:
# REPLACEME:3 actual variable predicate

PREFIX db: <http://data.local/rdf/ontology/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

ASK {
    db:REPLACEME1.REPLACEME5 rdf:type owl:Class .
}
